version: '2'

services:
  redis:
    image: resta/redis-ha
    environment:
      REDIS_HA_MASTER_PASSWORD: ${redis_password}

  sentinel:
    image: restra/redis-ha-sentinel
    environment:
      REDIS_HA_SENTINEL_MASTER_NAME: ${redis_sentinel_master_name}
      REDIS_HA_SENTINEL_QUORUM: ${redis_sentinel_quorum}
      REDIS_HA_SENTINEL_PASSWORD: ${redis_password}
    links:
      - redis